server:
  port: 8082
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:h2:mem:cardsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
    enabled: true
#   url: jdbc:h2:mem:testdb
#   driverClassName: org.h2.Driver
#   driverClassName: org.hibernate.dialect.MySQLDialect
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8088/"
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/