services:
  accounts:
    image: "nsree/accounts:v1"
    container_name: accounts_ms
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "nsree/loans:v1"
    container_name: loans_ms
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "nsree/cards:v1"
    container_name: cards_ms
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"
