spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8088/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
