server:
  port:
    8090
spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8088/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      customCircuit:
         slidingWindowSize: 10
         failureRateThreshold: 50
         waitDurationInOpenState: 10000
         permittedNumberOfCallsInHalfOpenState: 2
      controllerCircuit:
          slidingWindowSize: 10
          failureRateThreshold: 60
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 2
#         minimumNumberOfCalls: 1