server:
  port: 8089

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8088/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false