services:
  accounts:
    image: "nsree/accounts:latest"
    container_name: accounts_ms
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8088/"
      SPRING_PROFIES_ACTIVE: default
    depends_on:
      configserver:
        condition: service_healthy
  loans:
    image: "nsree/loans:latest"
    container_name: loans_ms
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8088/"
      SPRING_PROFIES_ACTIVE: default
  cards:
    image: "nsree/cards:latest"
    container_name: cards_ms
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8088/"
      SPRING_PROFIES_ACTIVE: default
  configserver:
    image: "nsree/configserver:latest"
    container_name: configserver_ms
    ports:
      - "8088:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: "rabbitmq:3.13-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bank
networks:
  bank:
    driver: "bridge"