
spring:
  application:
    name: "accounts"
  datasource:
#    url: jdbc:mysql://localhost:3301/accountsdb
    username: root
    password: root
  sql:
    inti:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
  profiles:
    active: "default"
#  config:
#    import: "optional:configserver:http://localhost:8088/"
management:
  endpoints:
    web:
      exposure:
        include: '*'
#accounts:
#  message: Welcome!
#  contactDetails:
#    name: sree
#    email: sree@gmail.com
#  onCallSupport:
#    - 989898
#    - 787665