server:
  port: 8081
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3301/accounts
    username: root
    password: root
  sql:
    inti:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8088/"
  management:
    endpoints:
      web:
        exposure:
          include: '*'
#accounts:
#  message: Welcome!
#  contactDetails:
#    name: sree
#    email: sree@gmail.com
#  onCallSupport:
#    - 989898
#    - 787665