server:
  port: 8081
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
    enabled: true
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
#      driverClassName: org.hibernate.dialect.MySQLDialect
#        url: jdbc:mysql://localhost:3301/accountsdb

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: "org.hibernate.dialect.MySQLDialect"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8088/"
management:
  endpoints:
    web:
      exposure:
        include: '*'
#accounts:
#  message: Welcome!
#  contactDetails:
#    name: sree
#    email: sree@gmail.com
#  onCallSupport:
#    - 989898
#    - 787665


#eureka config

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/